# Generated by Django 3.2.8 on 2021-10-23 07:11

from django.db import migrations, models
import django.db.models.deletion
import orders.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(validators=[orders.utils.validation_stock]),
        ),
    ]
