# Generated by Django 3.2.8 on 2021-10-23 11:33

from django.db import migrations, models
import orders.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(validators=[orders.utils.validation_stock]),
        ),
    ]
